version: "3.4"
services:
  editor:
    image: dtlfair/metadata-editor:2.1
    container_name: editor
    ports:
      - "127.0.0.1:8001:80"
    restart: unless-stopped
    volumes:
      - /data/apps/editor/config:/usr/share/nginx/html/conf
  
  fairifier:
    image: dtlfair/fairifier
    container_name: fairifier
    ports:
      - "127.0.0.1:8002:3333"
    depends_on:
      - virtuoso
    restart: unless-stopped
    volumes:
      - /data/apps/fairifier/data:/fairifier_data
      - /data/apps/fairifier/config:/configuration

  fdp:
    image: dtlfair/fdp
    container_name: fdp
    ports:
      - "127.0.0.1:8003:8080"
    depends_on:
      - agraph
    restart: unless-stopped

  search:
    image: dtlfair/search:develop
    container_name: search
    ports:
      - "127.0.0.1:8004:80"
      - "127.0.0.1:8084:8080"
      - "127.0.0.1:9200:9200"
    environment:
      - "ES_URL=http://localhost/searchserver"
    restart: unless-stopped

  virtuoso:
    image: tenforce/virtuoso
    container_name: virtuoso
    ports:
      - "127.0.0.1:8890:8890"
    restart: unless-stopped

  agraph:
    image: franzinc/agraph:v6.1.1
    container_name: agraph
    ports:
      - "127.0.0.1:10035:10035"
    restart: unless-stopped